/**
 * validate-document-snapshot.test.ts — Pre-extraction tripwire for v1.5.0 item A.
 *
 * Captures error code + message for a fixture matrix covering every doc-level
 * check (pageSize, margins, fonts, header/footer, defaultParagraphStyle,
 * sections, watermark, encryption, signature, bookmarks, hyphenation,
 * metadata). Used to guarantee bit-exact preservation when the inline
 * L104-382 block in validate/index.ts is extracted into validate/document.ts.
 *
 * Baseline is generated by running this test once on the pre-extraction
 * source; it then asserts equality on every subsequent run.
 *
 * Run: node --experimental-strip-types --test test/validate-document-snapshot.test.ts
 */
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const { validateDocument } = await import('../dist/index.js')

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const BASELINE = join(__dirname, 'data', 'validate-document-snapshot.json')

// Each fixture: name → minimal doc that triggers one specific doc-level check.
// All include valid content so we hit the doc-level checks (validate throws on
// the FIRST failure, so the order in validate() determines what's seen).
const goodContent = [{ type: 'paragraph' as const, text: 'ok' }]

const fixtures: Record<string, unknown> = {
  // ── pageSize ──
  'pageSize-bad-array': { content: goodContent, pageSize: [0, 100] },
  'pageSize-non-finite': { content: goodContent, pageSize: [Infinity, 100] },
  'pageSize-too-large': { content: goodContent, pageSize: [20000, 100] },

  // ── margins ──
  'margins-negative': { content: goodContent, margins: { top: -5 } },
  'margins-non-finite': { content: goodContent, margins: { left: Infinity } },
  'margins-page-too-small-width': { content: goodContent, pageSize: [100, 800], margins: { left: 60, right: 60 } },
  'margins-page-too-small-height': { content: goodContent, pageSize: [600, 100], margins: { top: 60, bottom: 60 } },

  // ── header / footer ──
  'header-text-not-string': { content: goodContent, header: { text: 123 } },
  'header-bad-fontSize': { content: goodContent, header: { text: 'x', fontSize: 0 } },
  'header-bad-align': { content: goodContent, header: { text: 'x', align: 'middle' } },
  'header-bad-fontWeight': { content: goodContent, header: { text: 'x', fontWeight: 500 } },
  'header-bad-color': { content: goodContent, header: { text: 'x', color: 'red' } },
  'footer-text-not-string': { content: goodContent, footer: { text: 123 } },

  // ── defaultParagraphStyle ──
  'dps-not-object': { content: goodContent, defaultParagraphStyle: 'no' },
  'dps-null': { content: goodContent, defaultParagraphStyle: null },
  'dps-bad-fontSize': { content: goodContent, defaultParagraphStyle: { fontSize: -1 } },
  'dps-bad-lineHeight': { content: goodContent, defaultParagraphStyle: { lineHeight: 0 } },
  'dps-bad-color': { content: goodContent, defaultParagraphStyle: { color: '#xyz123' } },
  'dps-bad-align': { content: goodContent, defaultParagraphStyle: { align: 'middle' } },
  'dps-bad-letterSpacing': { content: goodContent, defaultParagraphStyle: { letterSpacing: -1 } },
  'dps-bad-fontWeight': { content: goodContent, defaultParagraphStyle: { fontWeight: 500 } },

  // ── sections ──
  'sections-not-array': { content: goodContent, sections: 'no' },
  'sections-bad-fromPage': { content: goodContent, sections: [{ fromPage: 0 }] },
  'sections-bad-toPage': { content: goodContent, sections: [{ toPage: -1 }] },
  'sections-from-greater-than-to': { content: goodContent, sections: [{ fromPage: 5, toPage: 3 }] },
  'sections-header-text-not-string': { content: goodContent, sections: [{ header: { text: 1 } }] },
  'sections-header-bad-align': { content: goodContent, sections: [{ header: { text: 'x', align: 'mid' } }] },

  // ── watermark ──
  'watermark-empty': { content: goodContent, watermark: {} },
  'watermark-bad-opacity': { content: goodContent, watermark: { text: 'x', opacity: 2 } },
  'watermark-bad-fontSize': { content: goodContent, watermark: { text: 'x', fontSize: 0 } },
  'watermark-bad-fontWeight': { content: goodContent, watermark: { text: 'x', fontWeight: 500 } },
  'watermark-bad-color': { content: goodContent, watermark: { text: 'x', color: 'red' } },
  'watermark-non-finite-rotation': { content: goodContent, watermark: { text: 'x', rotation: Infinity } },
  'watermark-rotation-out-of-range': { content: goodContent, watermark: { text: 'x', rotation: 400 } },

  // ── encryption ──
  'encryption-userPassword-not-string': { content: goodContent, encryption: { userPassword: 123 } },
  'encryption-userPassword-empty': { content: goodContent, encryption: { userPassword: '' } },
  'encryption-ownerPassword-not-string': { content: goodContent, encryption: { ownerPassword: 123 } },
  'encryption-ownerPassword-empty': { content: goodContent, encryption: { ownerPassword: '' } },

  // ── signature ──
  'signature-bad-width': { content: goodContent, signature: { width: -1 } },
  'signature-bad-height': { content: goodContent, signature: { height: 0 } },
  'signature-bad-page': { content: goodContent, signature: { page: -1 } },
  'signature-bad-borderColor': { content: goodContent, signature: { borderColor: 'red' } },
  'signature-bad-fontSize': { content: goodContent, signature: { fontSize: 0 } },
  'signature-bad-p12-type': { content: goodContent, signature: { p12: 42 } },
  'signature-empty-p12-string': { content: goodContent, signature: { p12: '   ' } },
  'signature-bad-passphrase': { content: goodContent, signature: { passphrase: 42 } },
  'signature-bad-contactInfo': { content: goodContent, signature: { contactInfo: 42 } },
  'signature-bad-invisible': { content: goodContent, signature: { invisible: 'yes' } },
  'signature-and-encryption': {
    content: goodContent,
    signature: { p12: '/tmp/cert.p12' },
    encryption: { userPassword: 'pw' },
  },

  // ── bookmarks ──
  'bookmarks-bad-minLevel': { content: goodContent, bookmarks: { minLevel: 5 } },
  'bookmarks-bad-maxLevel': { content: goodContent, bookmarks: { maxLevel: 0 } },
  'bookmarks-min-greater-than-max': { content: goodContent, bookmarks: { minLevel: 4, maxLevel: 2 } },

  // ── hyphenation ──
  'hyphenation-no-language': { content: goodContent, hyphenation: {} },
  'hyphenation-bad-language': { content: goodContent, hyphenation: { language: 'en_US' } },
  'hyphenation-bad-minWordLength': { content: goodContent, hyphenation: { language: 'en-us', minWordLength: 1 } },
  'hyphenation-bad-leftMin': { content: goodContent, hyphenation: { language: 'en-us', leftMin: 0 } },
  'hyphenation-bad-rightMin': { content: goodContent, hyphenation: { language: 'en-us', rightMin: 10 } },

  // ── fonts (validateFontSpec) ──
  'fonts-empty-family': { content: goodContent, fonts: [{ family: '', src: 'x.ttf' }] },
  'fonts-bad-weight': { content: goodContent, fonts: [{ family: 'X', weight: 300, src: 'x.ttf' }] },
  'fonts-missing-src': { content: goodContent, fonts: [{ family: 'X' }] },
  'fonts-bad-style': { content: goodContent, fonts: [{ family: 'X', style: 'oblique', src: 'x.ttf' }] },
  'fonts-url-src': { content: goodContent, fonts: [{ family: 'X', src: 'http://evil.example.com/f.ttf' }] },

  // ── metadata ──
  'metadata-bad-language': { content: goodContent, metadata: { language: '' } },
  'metadata-bad-producer': { content: goodContent, metadata: { producer: '   ' } },

  // ── content guards (sanity, these stay in index.ts) ──
  'content-empty': { content: [] },
  'content-not-array': { content: 'no' },

  // ── valid doc (sanity, snapshot should show valid:true) ──
  'valid-minimal': { content: goodContent },
  'valid-with-options': {
    content: goodContent,
    pageSize: 'A4',
    margins: { top: 72, bottom: 72, left: 72, right: 72 },
    watermark: { text: 'DRAFT' },
  },
}

interface SnapshotEntry {
  valid: boolean
  errorCount: number
  errors: Array<{ code: string; message: string }>
}

function captureSnapshot(): Record<string, SnapshotEntry> {
  const out: Record<string, SnapshotEntry> = {}
  for (const [name, doc] of Object.entries(fixtures)) {
    const result = validateDocument(doc) as {
      valid: boolean
      errorCount: number
      errors: Array<{ code: string; message: string }>
    }
    out[name] = {
      valid: result.valid,
      errorCount: result.errorCount,
      errors: result.errors.map(e => ({ code: e.code, message: e.message })),
    }
  }
  return out
}

test('validate document-level snapshot tripwire (bit-exact error preservation)', () => {
  const captured = captureSnapshot()

  if (!existsSync(BASELINE) || process.env['UPDATE_SNAPSHOT'] === '1') {
    writeFileSync(BASELINE, JSON.stringify(captured, null, 2) + '\n', 'utf8')
    console.log(`[snapshot] Wrote baseline: ${BASELINE}`)
    return
  }

  const baseline = JSON.parse(readFileSync(BASELINE, 'utf8')) as Record<string, SnapshotEntry>

  // Check fixture set matches (no silent drops)
  const capturedKeys = Object.keys(captured).sort()
  const baselineKeys = Object.keys(baseline).sort()
  assert.deepEqual(
    capturedKeys,
    baselineKeys,
    'Snapshot fixture set drifted from baseline — regenerate with UPDATE_SNAPSHOT=1 if intentional',
  )

  // Per-fixture deep equality
  for (const name of capturedKeys) {
    assert.deepEqual(
      captured[name],
      baseline[name],
      `Snapshot drift for fixture "${name}". Run with UPDATE_SNAPSHOT=1 to regenerate if change is intentional.`,
    )
  }
})
