/**
 * Showcase: Professional Invoice
 * Real-world B2B invoice with GST, line items, company branding
 */
import { render } from '../dist/index.js'
import { writeFileSync, mkdirSync } from 'fs'
mkdirSync('output', { recursive: true })

const pdf = await render({
  pageSize: 'A4',
  margins: { top: 50, bottom: 50, left: 56, right: 56 },
  defaultFontSize: 10,
  footer: { text: 'Page {{pageNumber}} of {{totalPages}}  ·  Generated by pretext-pdf', fontSize: 8, color: '#aaaaaa', align: 'center' },
  content: [
    // Company name as large colored heading
    { type: 'heading', level: 1, text: 'Antigravity Systems', fontSize: 22, color: '#1a1a2e', spaceAfter: 2 },
    { type: 'paragraph', text: 'AI Infrastructure & Consulting  ·  Gurugram, Haryana  ·  GSTIN: 06AABCA1234Z1ZK', fontSize: 9, color: '#666666', spaceAfter: 2 },
    { type: 'paragraph', text: 'hello@antigravity.dev  ·  +91 98765 43210  ·  antigravity.dev', fontSize: 9, color: '#0070f3', spaceAfter: 16 },
    { type: 'hr', color: '#1a1a2e', thickness: 2, spaceBelow: 14 },

    // Invoice meta
    { type: 'heading', level: 3, text: 'INVOICE', fontSize: 18, color: '#1a1a2e', spaceAfter: 8 },
    {
      type: 'table',
      columns: [{ width: '1*' }, { width: '1*' }],
      rows: [
        { cells: [
          { text: 'Invoice No.\nINV-2026-0087' },
          { text: 'Bill To\nTata Consultancy Services Ltd.\nAttn: Finance, Powai, Mumbai 400076\nGSTIN: 27AAACT2727Q1ZW' },
        ]},
        { cells: [
          { text: 'Invoice Date\nApril 8, 2026' },
          { text: 'PO Reference\nTCS-PO-2026-4421' },
        ]},
        { cells: [
          { text: 'Due Date\nMay 8, 2026 (30 days)' },
          { text: 'Place of Supply\nMaharashtra (27)' },
        ]},
      ],
      borderColor: '#e8e8e8',
      borderWidth: 0.5,
      cellPaddingH: 10,
      cellPaddingV: 8,
      spaceAfter: 16,
    },

    // Line items
    { type: 'heading', level: 3, text: 'Services Rendered', color: '#1a1a2e', spaceAfter: 6 },
    {
      type: 'table',
      columns: [
        { width: '3*', align: 'left' },
        { width: 80, align: 'center' },
        { width: 90, align: 'right' },
        { width: 90, align: 'right' },
      ],
      rows: [
        { isHeader: true, cells: [
          { text: 'Description', fontWeight: 700, color: '#ffffff' },
          { text: 'Qty / Unit', fontWeight: 700, color: '#ffffff' },
          { text: 'Rate (Rs.)', fontWeight: 700, color: '#ffffff' },
          { text: 'Amount (Rs.)', fontWeight: 700, color: '#ffffff' },
        ]},
        { cells: [{ text: 'LLM Fine-tuning & Deployment Pipeline' }, { text: '1 project' }, { text: '2,50,000' }, { text: '2,50,000' }] },
        { cells: [{ text: 'AI Strategy Workshop (2 days, 15 attendees)' }, { text: '2 days' }, { text: '75,000' }, { text: '1,50,000' }] },
        { cells: [{ text: 'Dedicated ML Engineer (March 2026)' }, { text: '1 month' }, { text: '1,80,000' }, { text: '1,80,000' }] },
        { cells: [{ text: 'Data Pipeline Architecture Review' }, { text: '8 hrs' }, { text: '12,000' }, { text: '96,000' }] },
        { cells: [{ text: 'Infrastructure Setup (GCP + Kubernetes)' }, { text: 'Fixed' }, { text: '80,000' }, { text: '80,000' }] },
        { cells: [{ text: 'Monthly Support Retainer - April 2026' }, { text: '1 month' }, { text: '50,000' }, { text: '50,000' }] },
      ],
      headerBgColor: '#1a1a2e',
      borderColor: '#e0e0e0',
      borderWidth: 0.5,
      cellPaddingH: 8,
      cellPaddingV: 6,
      spaceAfter: 4,
    },

    // Totals
    { type: 'hr', color: '#e0e0e0', thickness: 0.5, spaceBelow: 6 },
    { type: 'paragraph', text: 'Subtotal:             Rs.8,06,000', align: 'right', spaceAfter: 3 },
    { type: 'paragraph', text: 'IGST @ 18%:           Rs.1,45,080', align: 'right', color: '#555555', spaceAfter: 6 },
    { type: 'hr', color: '#1a1a2e', thickness: 1, spaceBelow: 6 },
    { type: 'paragraph', text: 'TOTAL DUE:            Rs.9,51,080', fontSize: 14, fontWeight: 700, color: '#1a1a2e', align: 'right', spaceAfter: 4 },
    { type: 'paragraph', text: 'Amount in words: Rupees Nine Lakhs Fifty-One Thousand Eighty Only', fontSize: 9, color: '#666666', align: 'right', spaceAfter: 20 },

    // Payment + Notes
    { type: 'hr', color: '#e8e8e8', spaceBelow: 10 },
    {
      type: 'table',
      columns: [{ width: '1*' }, { width: '1*' }],
      rows: [
        { cells: [
          { text: 'Bank Details\nHDFC Bank, Cyber City Branch\nA/C: 5020 1234 5678\nIFSC: HDFC0001234\nUPI: pay@antigravity.dev' },
          { text: 'Terms & Conditions\n- Payment due within 30 days\n- Late fee: 1.5% per month\n- Disputes within 7 days of receipt\n- Subject to Gurugram jurisdiction' },
        ]},
      ],
      borderColor: '#e8e8e8',
      borderWidth: 0.5,
      cellPaddingH: 10,
      cellPaddingV: 8,
    },
  ],
})

writeFileSync('output/showcase-invoice.pdf', pdf)
console.log(`Done: showcase-invoice.pdf  (${(pdf.byteLength / 1024).toFixed(0)} KB)`)
