import { alignSchema, alignNoJustify, fontWeightSchema, colorSchema, dirSchema, spaceSchema, inlineSpanSchema } from './shared.js'

export const paragraphSchema = {
  type: 'object',
  required: ['type', 'text'],
  properties: {
    type: { type: 'string', const: 'paragraph' },
    text: { type: 'string' },
    dir: dirSchema,
    fontSize: { type: 'number' },
    lineHeight: { type: 'number' },
    fontFamily: { type: 'string' },
    fontWeight: fontWeightSchema,
    color: colorSchema,
    align: alignSchema,
    bgColor: colorSchema,
    spaceAfter: spaceSchema,
    spaceBefore: spaceSchema,
    keepTogether: { type: 'boolean' },
    underline: { type: 'boolean' },
    strikethrough: { type: 'boolean' },
    url: { type: 'string', format: 'uri' },
    letterSpacing: { type: 'number' },
    smallCaps: { type: 'boolean' },
    tabularNumbers: { type: 'boolean', description: 'Render digits at fixed slot width for aligned numeric columns.' },
    columns: { type: 'number', description: 'Number of columns for multi-column layout. Default: 1' },
    columnGap: { type: 'number', description: 'Gap between columns in pt. Default: 24' },
    hyphenate: { type: 'boolean', const: false, description: 'Set to false to disable hyphenation for this element.' },
    annotation: {
      type: 'object',
      required: ['contents'],
      properties: {
        contents: { type: 'string' },
        author: { type: 'string' },
        color: colorSchema,
        open: { type: 'boolean' },
      },
    },
  },
} as const

export const headingSchema = {
  type: 'object',
  required: ['type', 'level', 'text'],
  properties: {
    type: { type: 'string', const: 'heading' },
    level: { type: 'number', enum: [1, 2, 3, 4] },
    text: { type: 'string' },
    dir: dirSchema,
    fontFamily: { type: 'string' },
    fontWeight: fontWeightSchema,
    fontSize: { type: 'number' },
    lineHeight: { type: 'number' },
    align: alignSchema,
    color: colorSchema,
    bgColor: colorSchema,
    spaceBefore: spaceSchema,
    spaceAfter: spaceSchema,
    keepTogether: { type: 'boolean' },
    underline: { type: 'boolean' },
    strikethrough: { type: 'boolean' },
    bookmark: { type: 'boolean', const: false },
    anchor: { type: 'string' },
    url: { type: 'string', format: 'uri' },
    letterSpacing: { type: 'number' },
    smallCaps: { type: 'boolean' },
    tabularNumbers: { type: 'boolean', description: 'Render digits at fixed slot width for aligned numeric columns.' },
    hyphenate: { type: 'boolean', const: false, description: 'Set to false to disable hyphenation for this element.' },
    annotation: {
      type: 'object',
      required: ['contents'],
      properties: {
        contents: { type: 'string' },
        author: { type: 'string' },
        color: colorSchema,
        open: { type: 'boolean' },
      },
    },
  },
} as const

export const blockquoteSchema = {
  type: 'object',
  required: ['type', 'text'],
  properties: {
    type: { type: 'string', const: 'blockquote' },
    text: { type: 'string' },
    dir: dirSchema,
    borderColor: colorSchema,
    borderWidth: { type: 'number' },
    bgColor: colorSchema,
    color: colorSchema,
    fontFamily: { type: 'string' },
    fontWeight: fontWeightSchema,
    fontStyle: { type: 'string', enum: ['normal', 'italic'] },
    fontSize: { type: 'number' },
    lineHeight: { type: 'number' },
    padding: { type: 'number', description: 'Shorthand for paddingH and paddingV.' },
    paddingH: { type: 'number', description: 'Horizontal padding inside box in pt. Default: 16' },
    paddingV: { type: 'number', description: 'Vertical padding inside box in pt. Default: 10' },
    align: alignSchema,
    spaceBefore: spaceSchema,
    spaceAfter: spaceSchema,
    keepTogether: { type: 'boolean' },
    underline: { type: 'boolean' },
    strikethrough: { type: 'boolean' },
  },
} as const

export const codeSchema = {
  type: 'object',
  required: ['type', 'text', 'fontFamily'],
  properties: {
    type: { type: 'string', const: 'code' },
    text: { type: 'string' },
    fontFamily: { type: 'string', description: 'Monospace font family (must be loaded in doc.fonts)' },
    fontSize: { type: 'number' },
    lineHeight: { type: 'number' },
    bgColor: colorSchema,
    color: colorSchema,
    padding: { type: 'number' },
    spaceAfter: spaceSchema,
    spaceBefore: spaceSchema,
    keepTogether: { type: 'boolean' },
    language: { type: 'string', description: "e.g. 'javascript', 'typescript', 'python'" },
    dir: dirSchema,
    highlightTheme: {
      type: 'object',
      description: 'Custom syntax highlight colors (6-digit hex). Overrides default GitHub-light theme.',
      properties: {
        keyword: colorSchema,
        string: colorSchema,
        comment: colorSchema,
        number: colorSchema,
        function: colorSchema,
        punctuation: colorSchema,
        type: colorSchema,
        built_in: colorSchema,
        literal: colorSchema,
      },
    },
  },
} as const

export const calloutSchema = {
  type: 'object',
  required: ['type', 'content'],
  properties: {
    type: { type: 'string', const: 'callout' },
    content: { type: 'string' },
    style: { type: 'string', enum: ['info', 'warning', 'tip', 'note'] },
    title: { type: 'string' },
    backgroundColor: colorSchema,
    borderColor: colorSchema,
    color: colorSchema,
    titleColor: colorSchema,
    fontFamily: { type: 'string' },
    fontWeight: fontWeightSchema,
    fontSize: { type: 'number' },
    lineHeight: { type: 'number' },
    padding: { type: 'number', description: 'Shorthand for paddingH and paddingV. Default: 12' },
    paddingH: { type: 'number', description: 'Horizontal padding inside box in pt. Default: 16' },
    paddingV: { type: 'number', description: 'Vertical padding inside box in pt. Default: 10' },
    spaceBefore: spaceSchema,
    spaceAfter: spaceSchema,
    keepTogether: { type: 'boolean' },
    dir: dirSchema,
  },
} as const

export const richParagraphSchema = {
  type: 'object',
  required: ['type', 'spans'],
  properties: {
    type: { type: 'string', const: 'rich-paragraph' },
    spans: { type: 'array', items: inlineSpanSchema },
    dir: dirSchema,
    fontSize: { type: 'number' },
    lineHeight: { type: 'number' },
    align: alignSchema,
    bgColor: colorSchema,
    spaceBefore: spaceSchema,
    spaceAfter: spaceSchema,
    keepTogether: { type: 'boolean' },
    letterSpacing: { type: 'number' },
    smallCaps: { type: 'boolean' },
    tabularNumbers: { type: 'boolean', description: 'Render digits at fixed slot width for aligned numeric columns.' },
    columns: { type: 'number', description: 'Number of columns for multi-column layout. Default: 1' },
    columnGap: { type: 'number', description: 'Gap between columns in pt. Default: 24' },
  },
} as const

export const listSchema = {
  type: 'object',
  required: ['type', 'style', 'items'],
  properties: {
    type: { type: 'string', const: 'list' },
    style: { type: 'string', enum: ['ordered', 'unordered'] },
    items: {
      type: 'array',
      items: {
        type: 'object',
        required: ['text'],
        properties: {
          text: { type: 'string' },
          dir: dirSchema,
          fontWeight: fontWeightSchema,
          items: {
            type: 'array',
            description: 'Nested list items (up to 2 levels)',
            items: {
              type: 'object',
              required: ['text'],
              properties: {
                text: { type: 'string' },
                dir: dirSchema,
                fontWeight: fontWeightSchema,
              },
            },
          },
        },
      },
    },
    marker: { type: 'string' },
    indent: { type: 'number' },
    markerWidth: { type: 'number', description: 'Width reserved for marker column in pt. Default: 20' },
    fontSize: { type: 'number' },
    lineHeight: { type: 'number' },
    itemSpaceAfter: { type: 'number', description: 'Space between list items in pt. Default: 4' },
    nestedNumberingStyle: { type: 'string', enum: ['continue', 'restart'], description: 'How nested ordered counters behave. Default: continue' },
    color: colorSchema,
    spaceAfter: spaceSchema,
    spaceBefore: spaceSchema,
  },
} as const

export const tocSchema = {
  type: 'object',
  required: ['type'],
  properties: {
    type: { type: 'string', const: 'toc' },
    title: { type: 'string' },
    showTitle: { type: 'boolean' },
    minLevel: { type: 'number', enum: [1, 2, 3, 4] },
    maxLevel: { type: 'number', enum: [1, 2, 3, 4] },
    fontSize: { type: 'number' },
    titleFontSize: { type: 'number', description: 'Font size for TOC title. Default: fontSize + 4' },
    levelIndent: { type: 'number', description: 'Indentation per level in pt. Default: 16' },
    leader: { type: 'string', description: 'Leader character between entry and page number. Default: .' },
    entrySpacing: { type: 'number', description: 'Space after each entry line in pt. Default: 4' },
    fontFamily: { type: 'string' },
    spaceBefore: spaceSchema,
    spaceAfter: spaceSchema,
  },
} as const

export const footnoteDefSchema = {
  type: 'object',
  required: ['type', 'id', 'text'],
  properties: {
    type: { type: 'string', const: 'footnote-def' },
    id: { type: 'string' },
    text: { type: 'string' },
    fontSize: { type: 'number' },
    fontFamily: { type: 'string' },
    spaceAfter: spaceSchema,
  },
} as const

void alignNoJustify // imported for completeness — used by sub-schemas above
